# Generated by Django 3.2.8 on 2021-10-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtc',
            name='summary',
            field=models.TextField(default='this is cool'),
        ),
    ]
